### PR TITLE
Added the method and the various tests

### PR DESCRIPTION
**Pull request by cakeordeath83**
It looks like an enormous change because I needed to install bundler (huge file) so that I could install the RSpec gem. 

I'm still convinced there is an easier way to add testing...

### CODE REVIEW

**Comment by ndchorley** [comment]
A couple of things:

1. Don't commit dependencies to your repository (i.e. remove the .bundle directory) - it's unnecessary and kind of not a good thing to include a load of code that isn't yours! The Gemfile tells someone all they need to know about the dependencies.

2. For the purpose of this exercise, pretend that ```include?``` doesn't exist. Sorry, it's my fault for not specifying that earlier! I want to see how you go about solving that problem from first principles, as it were.

**Comment by cakeordeath83** [comment]
Ok doke, I'm on it!

**Comment by ndchorley** [comment]
Ruby's more helpful than I thought :(. Don't use ```select``` for this either! I haven't explained too well what I'm after. Imagine you had to implement ```include``` yourself. How would you do it? 

Another way of looking at this problem is like so: imagine I gave you a pile of numbered cards and asked you to tell me whether there was a card with 10 on it in the pile. How would you go about doing that?

I'm not trying to be mean! Problem solving like this will be very useful to you later on, so it's important to start with small problems like this.

**Comment by cakeordeath83** [comment]
Ha! No worries, I like being challenged!

**Comment by cakeordeath83** [comment]
Ok doke, hows that one? If it isn't what you're after, just let me know (I may need a point in the right direction after this one though...) and I'll give it another go!

**Comment by ndchorley** [comment]
Perfect!

**Comment by cakeordeath83** [comment]
Amazing, thank you so much (again!) for setting this up and guiding me through!

**Pull request merged**
